package br.gov.economia.receita.imp;

import br.gov.economia.receita.imp.standard.AbstractTransformer;

public class MotivoSituacaoCadastralTransformer extends AbstractTransformer {

  private static final String[] MOTIVO = new String[] {
    "EXTINÇÃO POR ENCERRAMENTO LIQUIDAÇÃO VOLUNTÁRIA",
    "INCORPORAÇÃO",
    "FUSÃO",
    "CISÃO TOTAL ",
    "ENCERRAMENTO DA FALÊNCIA",
    "ENCERRAMENTO DA LIQUIDAÇÃO",
    "ELEVAÇÃO A MATRIZ",
    "TRANSPASSE ",
    "NÃO INÍCIO DE ATIVIDADE",
    "EXTINÇÃO PELO ENCERRAMENTO DA LIQUIDAÇÃO JUDICIAL",
    "ANULAÇÃO POR MULTICIPLIDADE",
    "ANULAÇÃO ONLINE DE OFICIO",
    "OMISSA CONTUMAZ",
    "OMISSA NÃO LOCALIZADA",
    "INEXISTENTE DE FATO",
    "ANULAÇÃO POR VÍCIOS",
    "BAIXA INICIADA E AINDA NÃO DEFERIDA",
    "INTERRUPÇÃO TEMPORÁRIA DAS ATIVIDADES",
    "OMISSO DE DIRPJ ATÉ 5 EXERCÍCIOS",
    "EM CONDIÇÃO DE INAPTIDÃO",
    "PEDIDO DE BAIXA INDEFERIDA",
    "RESTABELECIMENTO COM CERTIDÃO POSITIVA COM EFEITO DE NEGATIVA",
    "COM PENDÊNCIA FISCAL",
    "POR EMISSÃO CERTIDÃO NEGATIVA",
    "CERTIDÃO POSITIVA COM EFEITO DE NEGATIVA",
    "IRREGULARIDADE DE PAGAMENTO",
    "IRREGULARIDADE DE RECOLHIMENTO E EXIGIBILIDADE SUSPENSA",
    "TRANSFERÊNCIA FILIAL CONDIÇÃO MATRIZ",
    "AGUARDANDO CONF. DE DIRPJ/DIPJ",
    "ANR - AGUARDANDO CONF. DE DIRPJ/DIPJ",
    "EXTINÇÃO DA FILIAL",
    "INEXISTENTE DE FATO – ADE/COSAR",
    "TRANSFERÊNCIA DO ÓRGÃO LOCAL A CONDIÇÃO DE FILIAL DO ÓRGÃO REGIONAL",
    "ANULAÇÃO DE INSCRIÇÃO INDEVIDA",
    "EMPRESA ESTRANGEIRA AGUARDANDO DOCUMENTAÇÃO",
    "PRÁTICA IRREGULAR DE OPERAÇÃO DE COMERCIO EXTERIOR",
    "BAIXA DE PRODUTOR RURAL",
    "BAIXA DEFERIDA PELA RFB AGUARDANDO ANALISE DO CONVENENTE",
    "BAIXA DEFERIDA PELA RFB E INDEFERIDA PELO CONVENENTE",
    "BAIXA INDEFERIDA PELA RFB E AGUARDANDO ANALISE DO CONVENENTE",
    "BAIXA INDEFERIDA PELA RFB E DEFERIDA PELO CONVENENTE",
    "BAIXA INDEFERIDA PELA RFB E SEFIN, AGUARDANDO ANALISE SEFAZ",
    "BAIXA DEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFAZ E INDEFERIDA PELA SEFIN",
    "BAIXA DEFERIDA PELA RFB E SEFAZ, AGUARDANDO ANALISE SEFIN",
    "BAIXA DEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFIN E INDEFERIDA PELA SEFAZ",
    "BAIXA DEFERIDA PELA RFB E SEFAZ E INDEFERIDA PELA SEFIN",
    "BAIXA DEFERIDA PELA RFB E SEFIN E INDEFERIDA PELA SEFAZ",
    "BAIXA INDEFERIDA PELA RFB, AGUARDANDO ANALISE SEFAZ E DEFERIDA PELA SEFIN",
    "BAIXA INDEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFAZ E INDEFERIDA PELA SEFIN",
    "BAIXA INDEFERIDA PELA RFB, DEFERIDA PELA SEFAZ E AGUARDANDO ANALISE DA SEFIN",
    "BAIXA INDEFERIDA PELA RFB E SEFAZ, AGUARDANDO ANALISE DA SEFIN",
    "BAIXA INDEFERIDA PELA RFB, DEFERIDA PELA SEFAZ E INDEFERIDA PELA SEFIN",
    "BAIXA INDEFERIDA PELA RFB E SEFAZ E DEFERIDA PELA SEFIN",
    "BAIXA - TRATAMENTO DIFERENCIADO DADO AS ME E EPP (LEI COMPLEMENTAR NUMERO 123/2006)",
    "DEFERIDO PELO CONVENENTE, AGUARDANDO ANALISE DA RFB",
    "ARTIGO 30, VI, DA IN 748/2007",
    "INDICIO INTERPOS. FRAUDULENTA",
    "FALTA DE PLURALIDADE DE SOCIOS",
    "OMISSÃO DE DECLARAÇÕES",
    "LOCALIZAÇÃO DESCONHECIDA",
    "INAPTIDÃO",
    "REGISTRO CANCELADO",
    "ANULAÇÃO POR NÃO CONFIRMADO ATO DE REGISTRO DO MEI NA JUNTA COMERCIAL",
    "INAPTIDÃO (LEI 11.941/2009 ART.54)",
    "DETERMINAÇÃO JUDICIAL",
    "OMISSÃO CONTUMAZ",
    "INCONSISTÊNCIA CADASTRAL",
    "BAIXA REGISTRADA NA JUNTA, INDEFERIDA NA RFB"
  };
  
  @Override
  protected String doTransform(String input) {
    int code = Strings.toInt(input, -1) - 1;
    if (code >= 0 && code < MOTIVO.length)
      return MOTIVO[code];
    return input;
  }
}

/*


 * */
