package br.gov.economia.receita.imp;

import java.util.HashMap;
import java.util.Map;

import br.gov.economia.receita.imp.standard.AbstractTransformer;

public class QualificacaoResponsavelTransformer extends AbstractTransformer{

  private static final Map<Integer, String> QUALIFICACAO = new HashMap<>();
  
  static {
    QUALIFICACAO.put(5," ADMINISTRADOR");
    QUALIFICACAO.put(10,"DIRETOR");
    QUALIFICACAO.put(11,"INTERVENTOR");
    QUALIFICACAO.put(12,"INVENTARIANTE");
    QUALIFICACAO.put(13,"LIQUIDANTE");
    QUALIFICACAO.put(16,"PRESIDENTE");
    QUALIFICACAO.put(17,"PROCURADOR");
    QUALIFICACAO.put(18,"SECRETÁRIO");
    QUALIFICACAO.put(19,"SÍNDICO (CONDOMÍNIO)");
    QUALIFICACAO.put(23,"SÓCIO CAPITALISTA");
    QUALIFICACAO.put(24,"SÓCIO COMANDITADO");
    QUALIFICACAO.put(31,"SÓCIO OSTENSIVO");
    QUALIFICACAO.put(32,"TABELIÃO");
    QUALIFICACAO.put(33,"TESOUREIRO");
    QUALIFICACAO.put(34,"TITULAR DE EMPRESA INDIVIDUAL IMOBILIÁRIA");
    QUALIFICACAO.put(39,"DIPLOMATA");
    QUALIFICACAO.put(40,"CÔNSUL");
    QUALIFICACAO.put(41,"REPRESENTANTE DE ORGANIZAÇÃO INTERNACIONAL");
    QUALIFICACAO.put(42,"OFICIAL DE REGISTRO");
    QUALIFICACAO.put(43,"RESPONSÁVEL");
    QUALIFICACAO.put(46,"MINISTRO DE ESTADO DAS RELAÇÕES EXTERIORES");
    QUALIFICACAO.put(49,"SÓCIO-ADMINISTRADOR");
    QUALIFICACAO.put(50,"EMPRESÁRIO");
    QUALIFICACAO.put(51,"CANDIDATO A CARGO POLÍTICO ELETIVO");
    QUALIFICACAO.put(54,"FUNDADOR");
    QUALIFICACAO.put(59,"PRODUTOR RURAL");
    QUALIFICACAO.put(60,"CÔNSUL HONORÁRIO");
    QUALIFICACAO.put(61,"RESPONSÁVEL INDÍGENA");
    QUALIFICACAO.put(62,"REPRESENTANTE DA INSTITUIÇÃO EXTRATERRITORIAL");
    QUALIFICACAO.put(64,"ADMINISTRADOR JUDICIAL");
    QUALIFICACAO.put(65,"TITULAR PESSOA FÍSICA RESIDENTE OU DOMICILIADO NO BRASIL");
    QUALIFICACAO.put(77,"VICE-PRESIDENTE");
  }

  @Override
  protected String doTransform(String input) {
    return QUALIFICACAO.getOrDefault(Strings.toInt(input, -1), input);
  }
}
